name: 'Single Line Slack Notification'
description: 'This action will send a single line notification to Slack'
author: 'speechanddebate'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'bell'
  color: 'yellow'
